FROM alpine:latest

RUN apk update && \
    apk add --no-cache \
        git \
        make \
        gcc \
        g++ \
        libc-dev \
        libstdc++ \
        linux-headers \
        bash \
        cmake \
        file \
        gdb \
        openocd \
        python3 \
        py3-pip \
        ninja \
        gcc-arm-none-eabi

RUN pip install pyelftools

# make -e CFLAGS="-I /usr/include"
